/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dolts.pokedex.HelperForms;

import com.dolts.pokedex.Helpers.RequestHelper;
import com.dolts.pokedex.models.Pokemon;
import com.fasterxml.jackson.databind.JsonNode;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Douglas.Oliveira
 */
public class CardWindow extends javax.swing.JFrame {

    private Pokemon pokemon;

    /**
     * Creates new form CardWindow
     */
    public CardWindow() {
        initComponents();
    }

    public CardWindow(int id) {
        initComponents();
        this.pokemon = new Pokemon();
        try {
            JsonNode rootNode = RequestHelper.sendRequest(String.valueOf(id));
            
            pokemon.parseAttributes(rootNode);
            setCardValues(pokemon);
        } catch (IOException ex) {
            Logger.getLogger(CardWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblHabilidadePrimaria = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblAtaque = new javax.swing.JLabel();
        lblAtaqueEspecial = new javax.swing.JLabel();
        lblTipoPrimario = new javax.swing.JLabel();
        lblTipoSecundario = new javax.swing.JLabel();
        lblHabilidadeSecundaria = new javax.swing.JLabel();
        lblVelocidade = new javax.swing.JLabel();
        lblDefesa = new javax.swing.JLabel();
        lblDefesaEspecial = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImage.setBackground(new java.awt.Color(0, 0, 0));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Imagem");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome");

        jLabel1.setText("HP ..............................");

        jLabel2.setText("Ataque .......................");

        jLabel3.setText("Ataque Especial ........");

        jLabel4.setText("Altura .........................");

        jLabel5.setText("Peso ................................");

        jLabel6.setText("Velocidade .....................");

        jLabel7.setText("Defesa .............................");

        jLabel8.setText("Defesa Especial ..............");

        jLabel9.setText("Tipo Primário ............");

        jLabel10.setText("Tipo Secundário ............");

        jLabel11.setText("Habilitade Primária ..");

        jLabel12.setText("Habilidade Secundária ..");

        lblHp.setText("0");

        lblHabilidadePrimaria.setText("0");

        lblAltura.setText("0");

        lblAtaque.setText("0");

        lblAtaqueEspecial.setText("0");

        lblTipoPrimario.setText("0");

        lblTipoSecundario.setText("0");

        lblHabilidadeSecundaria.setText("0");

        lblVelocidade.setText("0");

        lblDefesa.setText("0");

        lblDefesaEspecial.setText("0");

        lblPeso.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtaqueEspecial)
                    .addComponent(lblTipoPrimario)
                    .addComponent(lblHp)
                    .addComponent(lblHabilidadePrimaria)
                    .addComponent(lblAltura)
                    .addComponent(lblAtaque))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDefesaEspecial)
                    .addComponent(lblHabilidadeSecundaria)
                    .addComponent(lblTipoSecundario)
                    .addComponent(lblVelocidade)
                    .addComponent(lblDefesa)
                    .addComponent(lblPeso)))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNome)
                .addGap(12, 12, 12)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblVelocidade)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(lblHp))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDefesa)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(lblAtaque))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblAtaqueEspecial)
                    .addComponent(lblDefesaEspecial)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPeso)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblAltura))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(lblTipoPrimario)
                    .addComponent(lblTipoSecundario)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(lblHabilidadeSecundaria)
                    .addComponent(jLabel12)
                    .addComponent(lblHabilidadePrimaria)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAtaque;
    private javax.swing.JLabel lblAtaqueEspecial;
    private javax.swing.JLabel lblDefesa;
    private javax.swing.JLabel lblDefesaEspecial;
    private javax.swing.JLabel lblHabilidadePrimaria;
    private javax.swing.JLabel lblHabilidadeSecundaria;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTipoPrimario;
    private javax.swing.JLabel lblTipoSecundario;
    private javax.swing.JLabel lblVelocidade;
    // End of variables declaration//GEN-END:variables

    private void setCardValues(Pokemon p) {
        renderImage(p.getImagemURL());
        lblNome.setText(p.getNome());
        lblHp.setText(String.valueOf(p.getHp()));
        lblAtaque.setText(String.valueOf(p.getAtaque()));
        lblVelocidade.setText(String.valueOf(p.getVelocidade()));
        lblDefesa.setText(String.valueOf(p.getDefesa()));
        lblAtaqueEspecial.setText(String.valueOf(p.getAtaqueEspecial()));
        lblDefesaEspecial.setText(String.valueOf(p.getDefesaEspecial()));
        lblAltura.setText(String.valueOf(p.getAltura()));
        lblPeso.setText(String.valueOf(p.getPeso()));
        lblTipoPrimario.setText(String.valueOf(p.getTipo1()));
        lblTipoSecundario.setText(String.valueOf(p.getTipo2()));
        lblHabilidadePrimaria.setText(String.valueOf(p.getHabilidade1()));
        lblHabilidadeSecundaria.setText(String.valueOf(p.getHabilidade2()));
    }

    private void renderImage(String imageUrl) {
        try {
            URL url = new URL(imageUrl);
            Image image = ImageIO.read(url);

            if (image != null) { // Verifica se a imagem foi carregada corretamente
                // Redimensiona a imagem para caber na label (opcional, mas recomendado)
                int larguraLabel = lblImage.getWidth();
                int alturaLabel = lblImage.getHeight();

                // Evita redimensionamento com largura ou altura zero
                if (larguraLabel > 0 && alturaLabel > 0) {
                    Image imagemRedimensionada = image.getScaledInstance(larguraLabel, alturaLabel, Image.SCALE_SMOOTH);
                    lblImage.setIcon(new ImageIcon(imagemRedimensionada));
                } else {
                    lblImage.setIcon(new ImageIcon(image)); // Usa a imagem original se a label não tiver tamanho definido
                }
                lblImage.setText(""); // Limpa qualquer texto anterior na label
            } else {
                lblImage.setText("Imagem não encontrada.");
                lblImage.setIcon(null);
            }
        } catch (IOException e) {
            lblImage.setText("Erro ao carregar a imagem: " + e.getMessage());
            lblImage.setIcon(null);
            System.err.println("Erro ao carregar a imagem: " + e.getMessage()); // Imprime o erro no console para debug
        }
    }
}
